/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panels;

import view.model.StatusType;

/**
 *
 * @author Admin
 */
public class SanPhamPanel extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public SanPhamPanel() {
        initComponents();
        inputSanPham.hint = "San pham";
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.DANGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.DANGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.DANGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.DANGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.DANGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        table.addRow(new Object[]{"1","San pham 1",500,"Adidas",StatusType.KHONGHOATDONG});
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelBorder1 = new view.PanelBorder();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new view.component.Table();
        inputSanPham = new view.component.SearchText();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sản phẩm");

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Status"
            }
        ));
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSanPhamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.SearchText inputSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private view.PanelBorder panelBorder1;
    private view.component.Table table;
    // End of variables declaration//GEN-END:variables
}
