/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panels;

import domainmodels.SanPhamCT;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import services.impl.SanPhamCTImpl;
import view.model.StatusType;

/**
 *
 * @author Admin
 */
public class SanPhamCTPanel extends javax.swing.JPanel {
    SanPhamCTImpl spctService = new SanPhamCTImpl();
    /**
     * Creates new form SanPhamCTPanel
     */
    public SanPhamCTPanel() {
        initComponents();
        //LoadDataSPCT();
    }
//    private void LoadDataSPCT(){
//        DefaultTableModel tb = (DefaultTableModel) tableSPCT.getModel();
//        tb.setRowCount(0);
//        List<SanPhamCT> listSPCT = spctService.getALL();
//        for(SanPhamCT x: listSPCT){
//            //id_sanPham
//            int id_sanPham = x.getId_SanPham();
//            //String nameSP = sanPhamRepo.getNameByIDSP(id_sanPham);
//            
//            //id mau sac
//            int id_mauSac = x.getId_MauSac();
//            //String nameMS=mauSacRepo.getNameByID(id_mauSac);
//            //id thuong hieu
//            int id_thuongHieu = x.getId_ThuongHieu();
//            //String nameTH = thuongHieuRepo.getNameByID(id_thuongHieu);
//            //id kich thuoc
//            int id_kichThuoc =x.getId_KichThuoc();
//            //String nameKT = kichThuocrepo.getNameByID(id_kichThuoc);
//            //id_KieuDang;
//            int id_kieuDang=x.getId_KieuDang();
//            //String nameKD = kieuDangRepo.getNameByID(id_kieuDang);
//            //id_MuaPhuHop;
//            int id_muaPhuHop =x.getId_MuaPhuHop();
//            //String nameMPH= muaPHRepo.getNameByID(id_muaPhuHop);
//            //id_MDSD;
//            int id_MDSD = x.getId_MDSD();
//            //String nameMDSD= mucDichSDRepo.getNameByID(id_MDSD);
//            //id_ChatLieu;
//            int id_chatLieu=x.getId_ChatLieu();
//            //String nameCL =chatLieuRepo.getNameByID(id_chatLieu);
//            //id_HoaTiet;
//            int id_hoaTiet = x.getId_HoaTiet();
//            //String nameHT = hoaTietRepo.getNameByID(id_hoaTiet);
//            //id_HinhAnh;
//            int id_hinhAnh = x.getId_HinhAnh();
//            //String duongDanHA = hinhAnhRepo.getNameByID(id_hinhAnh);
//            //ma;
//            String ma = x.getMa();
//            //goi_Tinh;
//            boolean gioi_tinh = x.isGoi_Tinh();
//            String gioiTinh=null;
//            if(gioi_tinh==true){
//                gioiTinh="nam";
//            }else{
//                gioiTinh="Nu";
//            }
//            //so_Luong;
//            int so_Luong = x.getSo_Luong();
//            //gia;
//            float gia=x.getGia();
//            //mo_Ta;
//            String mo_ta=x.getMo_Ta();
//            //trang_thai;
//            int trang_thai =x.getTrang_thai();
//            boolean trangThai=true;
//            if(trang_thai==0){
//                trangThai=true;
//            }else{
//                trangThai=false;
//            }
//            tb.addRow(new Object[]{
//                id_hinhAnh, ma, id_sanPham,id_mauSac,id_thuongHieu, id_kichThuoc, id_kieuDang, so_Luong, gia, id_muaPhuHop,
//                id_MDSD, id_chatLieu, id_hoaTiet, gioiTinh, StatusType.DANGHOATDONG
//            });
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new view.component.Table();

        setPreferredSize(new java.awt.Dimension(908, 568));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private view.component.Table table1;
    // End of variables declaration//GEN-END:variables
}
